/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/type_and_value/type_and_value.ts:
/** @const */
var test_files$type_and_value$type_and_value = {};
/** @type {string} */
Node.prototype.extra;
// externs from test_files/type_and_value/typing.d.ts:
/**
 * @record
 * @struct
 */
function ExtTypeAndValue() {}
/** @type {number} */
ExtTypeAndValue.prototype.z;
/** @type {number} */
var ExtTypeAndValue;

/** @enum {number} */
var ExtEnum = {
  A: 1,
};
