/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
/**
 * @record
 * @struct
 * @suppress {duplicate}
 */
function ExportDeclaredIf() {}
 /** @type {number} */
ExportDeclaredIf.prototype.x;
/**
 * @type {number}
 * @suppress {duplicate}
 */
var exportedDeclaredVar;
/**
 * @constructor
 * @struct
 * @suppress {duplicate}
 */
function ExportDeclaredClass() {}
 /** @type {number} */
ExportDeclaredClass.prototype.x;

/**
 * @suppress {duplicate}
 * @return {string}
 */
function exportedDeclaredFn() {}
/**
 * @type {?}
 * @suppress {duplicate}
 */
var multiExportedDeclaredVar1;
/**
 * @type {number}
 * @suppress {duplicate}
 */
var multiExportedDeclaredVar2;
/**
 * @typedef {string}
 * @suppress {duplicate}
 */
var X;
