/**
 * @externs
 * @suppress {duplicate}
 */
// NOTE: generated by tsickle, do not edit.
/**
 * @record
 * @struct
 */
function ExportDeclaredIf() {}
 /** @type {number} */
ExportDeclaredIf.prototype.x;
 /** @type {number} */
var exportedDeclaredVar;
/**
 * @constructor
 * @struct
 */
function ExportDeclaredClass() {}
 /** @type {number} */
ExportDeclaredClass.prototype.x;

/**
 * @return {string}
 */
function exportedDeclaredFn() {}
 /** @type {?} */
var multiExportedDeclaredVar1;
 /** @type {number} */
var multiExportedDeclaredVar2;

/** @typedef {string} */
var X;
