/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/invalid_closure_properties/invalid_closure_properties.ts:
 /** @type {symbol} */
SymbolConstructor.prototype.observable;
