/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/invalid_closure_properties/invalid_closure_properties.ts
/** @const */
var test_files$invalid_closure_properties$invalid_closure_properties = {};
/** @const {symbol} */
SymbolConstructor.prototype.observable;
