/**
 * @externs
 * @suppress {duplicate,checkTypes,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/invalid_closure_properties/invalid_closure_properties.ts:
/** @const */
var test_files$invalid_closure_properties$invalid_closure_properties = {};
/** @type {symbol} */
SymbolConstructor.prototype.observable;
