/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/readonly/readonly.ts
/** @const */
var test_files$readonly$readonly = {};
/**
 * @record
 * @struct
 */
function DeclaredInterface() {}
/** @const {string} */
DeclaredInterface.prototype.prop;
