/**
 * @externs
 * @suppress {duplicate}
 */
// NOTE: generated by tsickle, do not edit.
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "goog:closure.Module"
/** @const */
tsickle_declare_module.goog_closure_Module = {};

/** @constructor @struct */
tsickle_declare_module.goog_closure_Module.X = function() {};

/* TODO: ExportAssignment in tsickle_declare_module.goog_closure_Module */
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "goog:closure.OtherModule"
/** @const */
tsickle_declare_module.goog_closure_OtherModule = {};

/** @constructor @struct */
tsickle_declare_module.goog_closure_OtherModule.SymA = function() {};

/** @constructor @struct */
tsickle_declare_module.goog_closure_OtherModule.SymB = function() {};

/* TODO: ExportDeclaration in tsickle_declare_module.goog_closure_OtherModule */
