/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/import_from_goog/decls.d.ts:
// Derived from: declare module "goog:closure.Module"
/** @const */
var goog_closure$Module = {};
/**
 * @constructor
 * @struct
 */
goog_closure$Module.X = function() {};
// Derived from: declare module "goog:closure.OtherModule"
/** @const */
var goog_closure$OtherModule = {};
/**
 * @constructor
 * @struct
 */
goog_closure$OtherModule.SymA = function() {};
/**
 * @constructor
 * @struct
 */
goog_closure$OtherModule.SymB = function() {};
