//!! generated by tsickle from test_files/ts_migration_exports_shim.no_externs.puretransform.declaration/correct_default_value_shorthand.ts
/**
 * @fileoverview An example export to be re-exported.
 * @suppress {visibility} :test_files_compilation_test
 */
export declare class MyDefaultClass {
    field: number;
}
declare global {
    namespace ಠ_ಠ.clutz {
        export { MyDefaultClass as module$contents$test_files$ts_migration_exports_shim$no_externs$puretransform$declaration$correct_default_value_shorthand_MyDefaultClass };
        export namespace module$exports$test_files$ts_migration_exports_shim$no_externs$puretransform$declaration$correct_default_value_shorthand {
            export { MyDefaultClass };
        }
    }
}
