/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/declare_function_repeated_tags/declare_function_repeated_tags.d.ts:

/**
 * This overload has docs and a tag. / This overload has the same. / And here is the actual implementation.
 * @export
 * @param {number|(string|number)} x is a string here / is a number here.
 * @return {?}
 */
function foo(x) {}
