/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/declare_var_and_ns/declare_var_and_ns.d.ts:
/** @type {!globalVariable.SomeInterface} */
var globalVariable;
/** @const */
var globalVariable = {};
/**
 * @record
 * @struct
 */
globalVariable.SomeInterface = function() {};
