/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/declare_var_and_ns/declare_var_and_ns.d.ts
/** @type {!globalVariable.SomeInterface} */
var globalVariable;
/** @const */
var globalVariable = {};
/**
 * @record
 * @struct
 */
globalVariable.SomeInterface = function() {};
