/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
/**
 * @const
 * @suppress {duplicate}
 */
var JSX = {};
/**
 * @record
 * @struct
 * @suppress {duplicate}
 */
JSX.Element = function() {};
/**
 * @record
 * @struct
 * @suppress {duplicate}
 */
JSX.IntrinsicElements = function() {};
 /** @type {?} */
JSX.IntrinsicElements.prototype.div;

/* TODO: PropertySignature: JSX."var" */
/**
 * @const
 * @suppress {duplicate}
 */
var React = {};

/**
 * @suppress {duplicate}
 * @param {...?} args
 * @return {!Element}
 */
React.createElement = function(args) {};

/**
 * @suppress {duplicate}
 * @param {!JSX.Element} element
 * @param {!HTMLElement} node
 * @return {void}
 */
React.render = function(element, node) {};
/**
 * @type {?}
 * @suppress {duplicate}
 */
var Component;
