/**
 * @externs
 * @suppress {duplicate,checkTypes,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/decorator_nested_scope/decorator_nested_scope.ts:
/** @const */
var test_files$decorator_nested_scope$decorator_nested_scope = {};
/** @type {?} */
var Component;
