/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/overload_with_this_parameter/overload_with_this_parameter.d.ts:
/**
 * @template T
 * @record
 * @struct
 */
function Foobar() {}

/**
 * @template U
 * @this {!Array<!Array<!Array<U>>>|!Array<!Array<U>>|!Array<U>}
 * @param {number|(undefined|number)=} depth The maximum recursion depth
 * @return {!Array<U>|!Array<?>}
 */
Foobar.prototype.flat = function(depth) {};
