/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/overload_with_this_parameter/overload_with_this_parameter.d.ts
/**
 * @record
 * @struct
 */
function Foo() {}

/**
 * @public
 * @this {!Foo|void}
 * @param {boolean|string|(undefined|number)=} x
 * @param {number=} y
 * @return {boolean|string|!Array<?>}
 */
Foo.prototype.bar = function(x, y) {};
