//!! generated by tsickle from test_files/interface_and_type.declaration/interface_and_type.ts
export interface Foo {
}
export type Bar = {};
declare global {
    namespace ಠ_ಠ.clutz {
        export { Bar as module$contents$test_files$interface_and_type$declaration$interface_and_type_Bar, Foo as module$contents$test_files$interface_and_type$declaration$interface_and_type_Foo };
        export namespace module$exports$test_files$interface_and_type$declaration$interface_and_type {
            export { Bar, Foo };
        }
    }
}
