/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.

// TODO(tsickle): ExportAssignment in namespace.d.ts
/** @const */
var SomeNamespace = {};
/**
 * @constructor
 * @struct
 */
SomeNamespace.Clazz = function() {};
