/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/declare_export_dts/declare_export_dts.d.ts
/** @const */
var test_files$declare_export_dts$declare_export_dts = {};
/**
 * @record
 * @struct
 */
test_files$declare_export_dts$declare_export_dts.InterfaceExportedInDts = function() {};
/** @type {!test_files$declare_export_dts$declare_export_dts.InterfaceUsedByExportedInDts} */
test_files$declare_export_dts$declare_export_dts.InterfaceExportedInDts.prototype.nestedInterface;
/** @type {!test_files$declare_export_dts$declare_export_dts.nestedNamespace.InterfaceNestedInNamespace} */
test_files$declare_export_dts$declare_export_dts.InterfaceExportedInDts.prototype.namespaceNestedInterface;
/** @type {!GlobalInterfaceDeclaredInExternalDts} */
test_files$declare_export_dts$declare_export_dts.InterfaceExportedInDts.prototype.globalInterface;
/**
 * @record
 * @struct
 */
test_files$declare_export_dts$declare_export_dts.InterfaceUsedByExportedInDts = function() {};
/** @type {string} */
test_files$declare_export_dts$declare_export_dts.InterfaceUsedByExportedInDts.prototype.property;
/** @const */
test_files$declare_export_dts$declare_export_dts.nestedNamespace = {};
/**
 * @record
 * @struct
 */
test_files$declare_export_dts$declare_export_dts.nestedNamespace.InterfaceNestedInNamespace = function() {};
/**
 * @record
 * @struct
 */
function GlobalInterfaceDeclaredInExternalDts() {}
// Derived from: declare module "ambient_external_module"
/** @const */
var ambient_external_module = {};
/**
 * @record
 * @struct
 */
ambient_external_module.InterfaceDeclaredInAmbientExternalModule = function() {};
/** @type {!ambient_external_module.InterfaceDeclaredInAmbientExternalModule} */
ambient_external_module.user;
// Derived from: declare module "./relative_ambient_external_module"
/** @const */
var test_files$declare_export_dts$relative_ambient_external_module = {};
/**
 * @record
 * @struct
 */
test_files$declare_export_dts$relative_ambient_external_module.InterfaceDeclaredInRelativeAmbientExternalModule = function() {};
/** @type {!test_files$declare_export_dts$relative_ambient_external_module.InterfaceDeclaredInRelativeAmbientExternalModule} */
test_files$declare_export_dts$relative_ambient_external_module.user;
// Generated from: test_files/declare_export_dts/declare_export_var.d.ts
/** @const */
var test_files$declare_export_dts$declare_export_var_ = {};
/** @type {!test_files$declare_export_dts$declare_export_var_.namespaceInDtsModule.InterfaceNestedInModuleScopedNamespace} */
test_files$declare_export_dts$declare_export_var_.variableDeclaredInDtsModule;
/** @type {!test_files$declare_export_dts$declare_export_var_.namespaceInDtsModule.InterfaceNestedInModuleScopedNamespace} */
var variableDeclaredInDtsModule;
/** @const */
test_files$declare_export_dts$declare_export_var_.namespaceInDtsModule = {};
/**
 * @record
 * @struct
 */
test_files$declare_export_dts$declare_export_var_.namespaceInDtsModule.InterfaceNestedInModuleScopedNamespace = function() {};
/**
 * export = variableDeclaredInDtsModule
 * @const
 */
var test_files$declare_export_dts$declare_export_var = test_files$declare_export_dts$declare_export_var_.variableDeclaredInDtsModule;
// export as namespace variableDeclaredInDtsModule
var variableDeclaredInDtsModule = test_files$declare_export_dts$declare_export_var_.variableDeclaredInDtsModule;
