/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/export_as_namespace_exporteq/export_as_namespace_exporteq.d.ts
/** @const */
var test_files$export_as_namespace_exporteq$export_as_namespace_exporteq_ = {};
/** @const */
test_files$export_as_namespace_exporteq$export_as_namespace_exporteq_.anamespace = {};
/**
 * @constructor
 * @struct
 */
test_files$export_as_namespace_exporteq$export_as_namespace_exporteq_.anamespace.NamespacedClass = function() {};

/**
 * @public
 * @return {string}
 */
test_files$export_as_namespace_exporteq$export_as_namespace_exporteq_.anamespace.NamespacedClass.prototype.method = function() {};
/**
 * export = anamespace
 * @const
 */
var test_files$export_as_namespace_exporteq$export_as_namespace_exporteq = test_files$export_as_namespace_exporteq$export_as_namespace_exporteq_.anamespace;
// export as namespace exportedNamespaceIncludingImportEq
var exportedNamespaceIncludingImportEq = test_files$export_as_namespace_exporteq$export_as_namespace_exporteq_.anamespace;
