/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/augment/angular/index.d.ts:
/** @const */
var test_files$augment$angular$index = {};
 /** @type {!IAngularStatic} */
test_files$augment$angular$index.angular;
/** @const */
test_files$augment$angular$index.angular = {};
/**
 * @record
 * @struct
 */
test_files$augment$angular$index.angular.Scope = function() {};
 /** @type {string} */
test_files$augment$angular$index.angular.Scope.prototype.name;
/** @const */
test_files$augment$angular$index.angular.sub = {};

/** @typedef {string} */
test_files$augment$angular$index.angular.sub.SubType;
/**
 * @record
 * @struct
 */
test_files$augment$angular$index.angular.IAngularStatic = function() {};
 /** @type {string} */
test_files$augment$angular$index.angular.IAngularStatic.prototype.version;

/**
 * @param {string} a
 * @return {string}
 */
test_files$augment$angular$index.angular.IAngularStatic.prototype.copy = function(a) {};
// export as namespace angular
var angular = test_files$augment$angular$index.angular;
// externs from test_files/augment/zz_angular-augment.d.ts:
/** @const */
var test_files$augment$zz_angular_augment = {};
// Derived from: declare module "./angular"
/**
 * @record
 * @struct
 */
test_files$augment$angular$index.sub.AugmentSubType = function() {};
 /** @type {string} */
test_files$augment$angular$index.sub.AugmentSubType.prototype.prop;
/** @const */
test_files$augment$angular$index.local = {};

/** @typedef {string} */
test_files$augment$angular$index.local.LocalType;

/** @typedef {!test_files.augment.angular.index.Scope} */
test_files$augment$angular$index.local.UsingSymbolFromAugmentedModule;
