/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.

/* TODO: ImportDeclaration in  */
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "./angular"
/** @const */
tsickle_declare_module.__angular = {};

/** @typedef {string} */
tsickle_declare_module.__angular.sub.AugmentSubType;
/** @const */
tsickle_declare_module.__angular.local = {};

/** @typedef {string} */
tsickle_declare_module.__angular.local.LocalType;

/* TODO: ExportAssignment in  */
 /** @type {string} */
var angular;
/**
 * @record
 * @struct
 */
angular.IFooBar = function() {};
 /** @type {string} */
angular.IFooBar.prototype.field;
/** @const */
angular.sub = {};

/** @typedef {string} */
angular.sub.SubType;

/* TODO: ExportAssignment in  */
 /** @type {string} */
var angular;
/**
 * @record
 * @struct
 */
angular.IFooBar = function() {};
 /** @type {string} */
angular.IFooBar.prototype.field;
/** @const */
angular.sub = {};

/** @typedef {string} */
angular.sub.SubType;
