/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.

// TODO(tsickle): ImportDeclaration in angular-augment.d.ts
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "./angular"

/** @typedef {string} */
tsickle_declare_module.__angular.sub.AugmentSubType;
/** @const */
tsickle_declare_module.__angular.local = {};

/** @typedef {string} */
tsickle_declare_module.__angular.local.LocalType;

// TODO(tsickle): ExportAssignment in index.d.ts
 /** @type {string} */
var angular;
/**
 * @record
 * @struct
 */
angular.IFooBar = function() {};
 /** @type {string} */
angular.IFooBar.prototype.field;
/** @const */
angular.sub = {};

/** @typedef {string} */
angular.sub.SubType;
