//!! generated by clutz.
/**
 * @fileoverview This file contains the Clutz output for a simple goog.provide.
 * It was manually created and is a support file for the actual test.
 */

declare namespace ಠ_ಠ.clutz.demo4 {
  function f(): void;
}
declare module 'goog:demo4' {
import demo4 = ಠ_ಠ.clutz.demo4;
  export = demo4;
}
