//!! generated by clutz.
/**
 * @fileoverview This file contains the Clutz output for a simple goog.module.
 * It was manually created and is a support file for the actual test.
 */

declare namespace ಠ_ಠ.clutz {
  class module$exports$demo3 {
    private noStructuralTyping_module$exports$demo3: any;
    bar(): void;
  }
}
declare module 'goog:demo3' {
import demo3 = ಠ_ಠ.clutz.module$exports$demo3;
  export default demo3;
}
