//!! generated by clutz.
/**
 * @fileoverview This file contains the Clutz output for a simple goog.module.
 * It was manually created and is a support file for the actual test.
 */

declare namespace ಠ_ಠ.clutz.module$exports$demo1 {
  class C {
    private noStructuralTyping_module$exports$demo1_C: any;
    foo(): void;
  }
}
declare module 'goog:demo1' {
import demo1 = ಠ_ಠ.clutz.module$exports$demo1;
  export = demo1;
}
