//!! generated by clutz.
/**
 * @fileoverview This file contains the Clutz output for a simple goog.module,
 * with a generic class.
 * It was manually created and is a support file for the actual test.
 */

declare namespace ಠ_ಠ.clutz.module$exports$demo6 {
  class C < T = any > {
    private noStructuralTyping_module$exports$demo6_C : [ T ];
    foo ( ) : void ;
  }
}
declare module 'goog:demo6' {
  import demo6 = ಠ_ಠ.clutz.module$exports$demo6;
  export = demo6;
}

