//!! generated by clutz2
/**
 * @fileoverview This file contains the Clutz2 output for a simple goog.provide.
 * It was manually created and is a support file for the actual test.
 */

declare namespace ಠ_ಠ.clutz {
	namespace demo8 {
		export class C {
			private noStructuralTyping_demo8$C: any;
		}
	}  // namespace demo8
}  // ಠ_ಠ.clutz

declare module 'goog:demo8' {
	import demo8 = ಠ_ಠ.clutz.demo8;
	export default demo8;
}
