//!! generated by clutz.
// Generated from closure_Module.js
declare namespace ಠ_ಠ.clutz {
  class module$exports$closure$types$Module {
    private noStructuralTyping_module$exports$closure$types$Module : any;
  }
}
// Generated from closure_Module.js
declare module 'goog:closure.types.Module' {
  import Module = ಠ_ಠ.clutz.module$exports$closure$types$Module;
  export default Module;
  const __clutz_actual_path: 'google3/closure_Module';
}
// Generated from closure_Module.js
declare module 'google3/closure_Module' {
  import Module = ಠ_ಠ.clutz.module$exports$closure$types$Module;
  export { Module };
  const __clutz_strip_property: 'Module';
  const __clutz_actual_namespace: 'closure.Module';
}

// Generated from closure_OtherModule.js
declare namespace ಠ_ಠ.clutz.module$exports$closure$types$OtherModule {
  class SymA {
    private noStructuralTyping_module$exports$closure$types$OtherModule_SymA : any;
  }
  class SymB {
    private noStructuralTyping_module$exports$closure$types$OtherModule_SymB : any;
  }
}
// Generated from closure_OtherModule.js
declare module 'goog:closure.types.OtherModule' {
  import OtherModule = ಠ_ಠ.clutz.module$exports$closure$types$OtherModule;
  export = OtherModule;
  const __clutz_actual_path: 'google3/closure_OtherModule';
}
// Generated from closure_OtherModule.js
declare module 'google3/closure_OtherModule' {
  import OtherModule = ಠ_ಠ.clutz.module$exports$closure$types$OtherModule;
  export = OtherModule;
  const __clutz_actual_namespace: 'closure.types.OtherModule';
}

// Generated from closure_LegacyModule.js
declare namespace ಠ_ಠ.clutz.closure.types.LegacyModule {
  export import LegacyExport = ಠ_ಠ.clutz.module$contents$closure$types$LegacyModule_LocalClass ;
}
// Generated from closure_LegacyModule.js
declare module 'goog:closure.types.LegacyModule' {
  import LegacyModule = ಠ_ಠ.clutz.closure.types.LegacyModule;
  export = LegacyModule;
  const __clutz_actual_path: 'google3/closure_LegacyModule';
}
// Generated from closure_LegacyModule.js
declare module 'google3/closure_LegacyModule' {
  import LegacyModule = ಠ_ಠ.clutz.closure.types.LegacyModule;
  export = LegacyModule;
  const __clutz_actual_namespace: 'closure.types.LegacyModule';
}
// Generated from closure_LegacyModule.js
declare namespace ಠ_ಠ.clutz {
  class module$contents$closure$types$LegacyModule_LocalClass {
    private noStructuralTyping_module$contents$closure$types$LegacyModule_LocalClass : any;
  }
}
// Aliases of namespaces that came from declareLegacyNamespace modules
declare namespace ಠ_ಠ.clutz {
  export import module$exports$closure$types$LegacyModule = ಠ_ಠ.clutz.closure.types.LegacyModule ;
}
