/**
 * @externs
 * @suppress {duplicate,checkTypes,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/export_default_dts/export_default.d.ts:
/** @const */
var test_files$export_default_dts$export_default = {};
/** @const */
test_files$export_default_dts$export_default.innerNamespace = {};
/**
 * @constructor
 * @struct
 */
test_files$export_default_dts$export_default.innerNamespace.DefaultExportedClass = function() {};
/** @type {string} */
test_files$export_default_dts$export_default.innerNamespace.DefaultExportedClass.prototype.property;
/** @const */
test_files$export_default_dts$export_default.default = test_files$export_default_dts$export_default.innerNamespace.DefaultExportedClass;
