/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/declare_enum/declare_enum.d.ts

/** @enum {number} */
var AmbientEnum = {
  ENUM_MEMBER_1: 1,
  ENUM_MEMBER_2: 1,
};

/** @enum {string} */
var AmbientStringEnum = {
  ENUM_MEMBER_1: '',
  ENUM_MEMBER_2: '',
};

/** @enum {?} */
var MixedAmbientEnum = {
  ENUM_MEMBER_1: 1,
  ENUM_MEMBER_2: 1,
};

/** @enum {number} */
var StringKeyEnum = {
  foo: 1,
  /* TODO: StringLiteral: '.tricky.invalid name' */
};
/** @const */
var namespaceWithEnums = {};

/** @enum {number} */
namespaceWithEnums.EnumInNamespace = {
  V: 1,
};
