goog.module('sickle_test.enum.untyped');
let EnumUntypedTest1 = {};
EnumUntypedTest1.XYZ = 0;
EnumUntypedTest1.PI = 3.14159;
EnumUntypedTest1[EnumUntypedTest1.XYZ] = "XYZ";
EnumUntypedTest1[EnumUntypedTest1.PI] = "PI";
exports.EnumUntypedTest2 = {};
exports.EnumUntypedTest2.XYZ = 0;
exports.EnumUntypedTest2.PI = 3.14159;
exports.EnumUntypedTest2[exports.EnumUntypedTest2.XYZ] = "XYZ";
exports.EnumUntypedTest2[exports.EnumUntypedTest2.PI] = "PI";
