/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/declare_export_global/declare_export_global.d.ts
/** @const */
var test_files$declare_export_global$declare_export_global_ = {};
/** @const */
var globalNamespace = {};
/** @type {number} */
globalNamespace.x;
/**
 * export = globalNamespace
 * @const
 */
var test_files$declare_export_global$declare_export_global = globalNamespace;
// Generated from: test_files/declare_export_global/declare_export_global_nested.d.ts
/** @const */
var test_files$declare_export_global$declare_export_global_nested_ = {};
/** @const */
var globalParentNamespace = {};
/** @const */
globalParentNamespace.globalNestedNamespace = {};
/** @type {number} */
globalParentNamespace.globalNestedNamespace.x;
/**
 * export = globalParentNamespace.globalNestedNamespace
 * @const
 */
var test_files$declare_export_global$declare_export_global_nested = test_files$declare_export_global$declare_export_global_nested_;
