/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/declare_export.untyped/declare_export.ts
/** @const */
var test_files$declare_export$untyped$declare_export = {};
/**
 * @record
 * @struct
 */
test_files$declare_export$untyped$declare_export.ExportDeclaredIf = function() {};
/** @type {?} */
test_files$declare_export$untyped$declare_export.ExportDeclaredIf.prototype.x;
/** @type {?} */
test_files$declare_export$untyped$declare_export.exportedDeclaredVar;
/**
 * @constructor
 * @struct
 */
test_files$declare_export$untyped$declare_export.ExportDeclaredClass = function() {};
/** @type {?} */
test_files$declare_export$untyped$declare_export.ExportDeclaredClass.prototype.x;

/**
 * @return {?}
 */
test_files$declare_export$untyped$declare_export.exportedDeclaredFn = function() {};
/** @type {?} */
test_files$declare_export$untyped$declare_export.multiExportedDeclaredVar1;
/** @type {?} */
test_files$declare_export$untyped$declare_export.multiExportedDeclaredVar2;

/** @typedef {?} */
test_files$declare_export$untyped$declare_export.X;

/** @enum {number} */
test_files$declare_export$untyped$declare_export.ExportDeclaredEnum = {
  VALUE: 1,
};
