/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
/**
 * @const
 * @suppress {duplicate}
 */
var exportedDeclaredNamespace = {};
/**
 * @record
 * @struct
 * @suppress {duplicate}
 */
exportedDeclaredNamespace.Used = function() {};
/**
 * @record
 * @struct
 * @suppress {duplicate}
 */
exportedDeclaredNamespace.User = function() {};
 /** @type {!exportedDeclaredNamespace.Used} */
exportedDeclaredNamespace.User.prototype.field;
/**
 * @const
 * @suppress {duplicate}
 */
var nested = {};
/**
 * @const
 * @suppress {duplicate}
 */
nested.exportedNamespace = {};
/**
 * @record
 * @struct
 * @suppress {duplicate}
 */
nested.exportedNamespace.Used = function() {};
/**
 * @record
 * @struct
 * @suppress {duplicate}
 */
nested.exportedNamespace.User = function() {};
 /** @type {!nested.exportedNamespace.Used} */
nested.exportedNamespace.User.prototype.field;
/**
 * @const
 * @suppress {duplicate}
 */
var globalNamespace = {};
/**
 * @constructor
 * @struct
 * @suppress {duplicate}
 */
globalNamespace.ClassInGlobal = function() {};
 /** @type {!nested.exportedNamespace.Used} */
globalNamespace.ClassInGlobal.prototype.field;
/**
 * @const
 * @suppress {duplicate}
 */
var exportedNamespaceUsingGlobal = {};
/**
 * @record
 * @struct
 * @suppress {duplicate}
 */
exportedNamespaceUsingGlobal.User = function() {};
 /** @type {!globalNamespace.ClassInGlobal} */
exportedNamespaceUsingGlobal.User.prototype.field;
/**
 * @const
 * @suppress {duplicate}
 */
var exportedNamespaceUsingModuleType = {};
/**
 * @record
 * @struct
 * @suppress {duplicate}
 */
exportedNamespaceUsingModuleType.User = function() {};
 /** @type {?} */
exportedNamespaceUsingModuleType.User.prototype.field;
