/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/export_declare_namespace/export_declare_namespace.ts
/** @const */
var test_files$export_declare_namespace$export_declare_namespace = {};
/** @const */
test_files$export_declare_namespace$export_declare_namespace.exportedDeclaredNamespace = {};
/**
 * @record
 * @struct
 */
test_files$export_declare_namespace$export_declare_namespace.exportedDeclaredNamespace.Used = function() {};
/**
 * @record
 * @struct
 */
test_files$export_declare_namespace$export_declare_namespace.exportedDeclaredNamespace.User = function() {};
/** @type {!test_files$export_declare_namespace$export_declare_namespace.exportedDeclaredNamespace.Used} */
test_files$export_declare_namespace$export_declare_namespace.exportedDeclaredNamespace.User.prototype.fieldFromLocalNamespace;
/** @type {!test_files$export_declare_namespace$export_declare_namespace.nested.exportedNamespace.Used} */
test_files$export_declare_namespace$export_declare_namespace.exportedDeclaredNamespace.User.prototype.fieldFromOtherNamespace;
/** @const */
test_files$export_declare_namespace$export_declare_namespace.nested = {};
/** @const */
test_files$export_declare_namespace$export_declare_namespace.nested.exportedNamespace = {};
/**
 * @record
 * @struct
 */
test_files$export_declare_namespace$export_declare_namespace.nested.exportedNamespace.Used = function() {};
/**
 * @record
 * @struct
 */
test_files$export_declare_namespace$export_declare_namespace.nested.exportedNamespace.User = function() {};
/** @type {!test_files$export_declare_namespace$export_declare_namespace.nested.exportedNamespace.Used} */
test_files$export_declare_namespace$export_declare_namespace.nested.exportedNamespace.User.prototype.fieldFromLocalNamespace;
/** @type {!test_files$export_declare_namespace$export_declare_namespace.exportedDeclaredNamespace.Used} */
test_files$export_declare_namespace$export_declare_namespace.nested.exportedNamespace.User.prototype.fieldFromOtherNamespace;
/** @const */
var globalNamespace = {};
/**
 * @constructor
 * @struct
 */
globalNamespace.ClassInGlobal = function() {};
/** @type {!test_files$export_declare_namespace$export_declare_namespace.nested.exportedNamespace.Used} */
globalNamespace.ClassInGlobal.prototype.field;
/** @const */
test_files$export_declare_namespace$export_declare_namespace.exportedNamespaceUsingGlobal = {};
/**
 * @record
 * @struct
 */
test_files$export_declare_namespace$export_declare_namespace.exportedNamespaceUsingGlobal.User = function() {};
/** @type {!globalNamespace.ClassInGlobal} */
test_files$export_declare_namespace$export_declare_namespace.exportedNamespaceUsingGlobal.User.prototype.field;
/** @const */
test_files$export_declare_namespace$export_declare_namespace.exportedNamespaceUsingModuleType = {};
/**
 * @record
 * @struct
 */
test_files$export_declare_namespace$export_declare_namespace.exportedNamespaceUsingModuleType.User = function() {};
/** @type {?} */
test_files$export_declare_namespace$export_declare_namespace.exportedNamespaceUsingModuleType.User.prototype.field;
