/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/import_equals/exporter.d.ts
/** @const */
var test_files$import_equals$exporter = {};
/** @const */
test_files$import_equals$exporter.exportedSymbol = {};
/** @type {number} */
test_files$import_equals$exporter.exportedSymbol.valueInNamespace;
/**
 * @constructor
 * @struct
 */
test_files$import_equals$exporter.Exported = function() {};
/**
 * @constructor
 * @struct
 */
test_files$import_equals$exporter.Exported.Nested = function() {};

/** @enum {number} */
test_files$import_equals$exporter.Exported.Nested.Thing = {
  ITEM: 1,
};
// Generated from: test_files/import_equals/import_equals_global.d.ts
/** @const */
var __React = {};
/**
 * @constructor
 * @struct
 */
__React.X = function() {};
/** @const */
var importEquals = {};
/** @const */
importEquals.React = __React;
/** @const */
var React = __React;
// Generated from: test_files/import_equals/import_equals_module.d.ts
/** @const */
var test_files$import_equals$import_equals_module_ = {};
/** @const */
test_files$import_equals$import_equals_module_.alias = test_files$import_equals$import_equals_module_.namespaceInModule;
/** @const */
test_files$import_equals$import_equals_module_.Exported = test_files$import_equals$exporter.Exported;
/** @const */
test_files$import_equals$import_equals_module_.namespaceInModule = {};
/**
 * @constructor
 * @struct
 */
test_files$import_equals$import_equals_module_.namespaceInModule.InNamespace = function() {};
/** @type {!test_files$import_equals$import_equals_module_.namespaceInModule.InNamespace} */
test_files$import_equals$import_equals_module_.namespaceInModule.myVar;
/** @type {!test_files$import_equals$exporter.Exported.Nested} */
test_files$import_equals$import_equals_module_.namespaceInModule.otherVar;
/** @const */
var globalNamespaceInModule = {};
/** @type {number} */
globalNamespaceInModule.globalSymbolInModule;
/** @const */
test_files$import_equals$import_equals_module_.globalNamespaceRenamedInModule = globalNamespaceInModule;
/** @const */
test_files$import_equals$import_equals_module_.globalNamespaceFromOtherFileAliasedInModule = React;
/** @const */
test_files$import_equals$import_equals_module_.aliasForImportedSymbol = test_files$import_equals$exporter.exportedSymbol;
/**
 * export = namespaceInModule
 * @const
 */
var test_files$import_equals$import_equals_module = test_files$import_equals$import_equals_module_.namespaceInModule;
