/**
 * @externs
 * @suppress {duplicate,checkTypes,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/interface/interface_extends.ts
/** @const */
var aNamespace = {};

/**
 * @return {void}
 */
aNamespace.aFunction = function() {};
