/**
 * @externs
 * @suppress {duplicate}
 */
// NOTE: generated by tsickle, do not edit.

/**
 * @constructor
 * @struct
 */
function MultipleConstructorsOptional() {}

/**
 * @constructor
 * @struct
 * @param {boolean} a
 */
function MultipleConstructorsTypes(a) {}

/**
 * @constructor
 * @struct
 * @param {boolean} a
 */
function MultipleConstructorsNamesAndTypes(a) {}

/**
 * @constructor
 * @struct
 * @param {number} a
 * @param {number} b
 * @param {number} c
 * @param {string=} normal
 * @param {boolean=} color
 * @param {number=} materialIndex
 */
function MultipleConstructorsComplexMatrix(a, b, c, normal, color, materialIndex) {}

/**
 * @constructor
 * @struct
 * @param {...number} a
 */
function MultipleConstructorsVariadic(a) {}

/**
 * @constructor
 * @struct
 * @param {Array<string>} points
 */
function MultipleConstructorsVariadicNames(points) {}
/** @constructor @struct */
function OverloadSimpleArgs() {}

/**
 * @param {string} a
 * @return {void}
 */
OverloadSimpleArgs.prototype.o = function(a) {};

/**
 * @param {string} a
 * @param {boolean} b
 * @return {void}
 */
OverloadSimpleArgs.prototype.o = function(a, b) {};

/**
 * @param {string} a
 * @param {boolean} b
 * @param {number} c
 * @return {void}
 */
OverloadSimpleArgs.prototype.o = function(a, b, c) {};
/** @constructor @struct */
function OverloadNameVariants() {}

/**
 * @param {string} a
 * @return {void}
 */
OverloadNameVariants.prototype.o = function(a) {};

/**
 * @param {boolean} b
 * @return {void}
 */
OverloadNameVariants.prototype.o = function(b) {};

/**
 * @param {number} c
 * @return {void}
 */
OverloadNameVariants.prototype.o = function(c) {};
/** @constructor @struct */
function OverloadReturnTypesNoVoid() {}

/**
 * @param {string} a
 * @param {boolean} b
 * @return {boolean}
 */
OverloadReturnTypesNoVoid.prototype.o = function(a, b) {};

/**
 * @param {string} a
 * @param {boolean} b
 * @param {number} c
 * @return {number}
 */
OverloadReturnTypesNoVoid.prototype.o = function(a, b, c) {};
/** @constructor @struct */
function OverloadReturnTypesWithVoid() {}

/**
 * @param {string} a
 * @return {void}
 */
OverloadReturnTypesWithVoid.prototype.o = function(a) {};

/**
 * @param {string} a
 * @param {boolean} b
 * @return {boolean}
 */
OverloadReturnTypesWithVoid.prototype.o = function(a, b) {};

/**
 * @param {string} a
 * @param {boolean} b
 * @param {number} c
 * @return {number}
 */
OverloadReturnTypesWithVoid.prototype.o = function(a, b, c) {};
/** @constructor @struct */
function OverloadBigMix() {}

/**
 * @param {string} a
 * @return {void}
 */
OverloadBigMix.prototype.o = function(a) {};

/**
 * @param {string} a
 * @param {number} b
 * @return {number}
 */
OverloadBigMix.prototype.o = function(a, b) {};

/**
 * @param {number} c
 * @param {number} b
 * @return {number}
 */
OverloadBigMix.prototype.o = function(c, b) {};

/**
 * @param {Array<OverloadBigMix>} e
 * @return {boolean}
 */
OverloadBigMix.prototype.o = function(e) {};

/**
 * @param {...OverloadBigMix} f
 * @return {number}
 */
OverloadBigMix.prototype.o = function(f) {};
