//!! generated by tsickle from test_files/reexport.declaration/renamed_export.ts
import { OTHER } from './export';
export { OTHER as MOTHER };
declare global {
    namespace ಠ_ಠ.clutz {
        export { OTHER as module$contents$test_files$reexport$declaration$renamed_export_MOTHER };
        export namespace module$exports$test_files$reexport$declaration$renamed_export {
            export { OTHER as MOTHER };
        }
    }
}
