/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/type/type.ts:
/** @const */
var test_files$type$type = {};
/** @type {boolean} */
Array.prototype.monkeyPatch;
