/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/underscore/underscore.ts
/** @const */
var test_files$underscore$underscore = {};
/** @const */
var __NS = {};
/** @type {number} */
__NS.__ns1;
