/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
/**
 * @const
 * @suppress {duplicate}
 */
var __NS = {};
/**
 * @type {number}
 * @suppress {duplicate}
 */
__NS.__ns1;
