/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/declare_extends/declare_extends.d.ts
/**
 * @constructor
 * @struct
 */
function Parent() {}
/** @type {number} */
Parent.prototype.x;
/**
 * @extends {Parent}
 * @constructor
 * @struct
 */
function Child() {}
/** @type {number} */
Child.prototype.y;
/**
 * @record
 * @struct
 */
function ParentInterface() {}

/**
 * @public
 * @return {void}
 */
ParentInterface.prototype.foo = function() {};
/**
 * @extends {ParentInterface}
 * @record
 * @struct
 */
function ChildInterface() {}

/**
 * @public
 * @return {void}
 */
ChildInterface.prototype.bar = function() {};
/**
 * @implements {ParentInterface}
 * @constructor
 * @struct
 */
function ImplementingClass() {}

/**
 * @public
 * @return {void}
 */
ImplementingClass.prototype.foo = function() {};
/** @const */
var foo = {};
/**
 * @constructor
 * @struct
 */
foo.NamespacedParent = function() {};
/** @type {number} */
foo.NamespacedParent.prototype.x;
/**
 * @extends {foo.NamespacedParent}
 * @constructor
 * @struct
 */
foo.NamespacedChildSameNamespace = function() {};
/** @type {number} */
foo.NamespacedChildSameNamespace.prototype.y;
/** @const */
var bar = {};
/**
 * @extends {foo.NamespacedParent}
 * @constructor
 * @struct
 */
bar.NamespacedChild = function() {};
/** @type {number} */
bar.NamespacedChild.prototype.y;
