/**
 * @externs
 * @suppress {duplicate}
 */
// NOTE: generated by tsickle, do not edit.
/**
 * @constructor
 * @struct
 */
function Parent() {}
 /** @type {number} */
Parent.prototype.x;
/**
 * @extends {Parent}
 * @constructor
 * @struct
 */
function Child() {}
 /** @type {number} */
Child.prototype.y;
/**
 * @record
 * @struct
 */
function ParentInterface() {}

/**
 * @return {void}
 */
ParentInterface.prototype.foo = function() {};
/**
 * @extends {ParentInterface}
 * @record
 * @struct
 */
function ChildInterface() {}

/**
 * @return {void}
 */
ChildInterface.prototype.bar = function() {};
/**
 * @implements {ParentInterface}
 * @constructor
 * @struct
 */
function ImplementingClass() {}

/**
 * @return {void}
 */
ImplementingClass.prototype.foo = function() {};
