/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
/**
 * @constructor
 * @struct
 * @suppress {duplicate}
 */
function Parent() {}
 /** @type {number} */
Parent.prototype.x;
/**
 * @extends {Parent}
 * @constructor
 * @struct
 * @suppress {duplicate}
 */
function Child() {}
 /** @type {number} */
Child.prototype.y;
/**
 * @record
 * @struct
 * @suppress {duplicate}
 */
function ParentInterface() {}

/**
 * @return {void}
 */
ParentInterface.prototype.foo = function() {};
/**
 * @extends {ParentInterface}
 * @record
 * @struct
 * @suppress {duplicate}
 */
function ChildInterface() {}

/**
 * @return {void}
 */
ChildInterface.prototype.bar = function() {};
/**
 * @implements {ParentInterface}
 * @constructor
 * @struct
 * @suppress {duplicate}
 */
function ImplementingClass() {}

/**
 * @return {void}
 */
ImplementingClass.prototype.foo = function() {};
/**
 * @const
 * @suppress {duplicate}
 */
var foo = {};
/**
 * @constructor
 * @struct
 * @suppress {duplicate}
 */
foo.NamespacedParent = function() {};
 /** @type {number} */
foo.NamespacedParent.prototype.x;
/**
 * @const
 * @suppress {duplicate}
 */
var bar = {};
/**
 * @extends {foo.NamespacedParent}
 * @constructor
 * @struct
 * @suppress {duplicate}
 */
bar.NamespacedChild = function() {};
 /** @type {number} */
bar.NamespacedChild.prototype.y;
