/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/declare_generic/declare_generic.d.ts:
/**
 * @template T, U
 * @constructor
 * @struct
 */
function WithGeneric() {}

/**
 * @param {T} t
 * @return {U}
 */
WithGeneric.prototype.useGenericType = function(t) {};

/**
 * @template T
 * @return {T}
 */
function genericFn() {}
