/**
 * @externs
 * @suppress {duplicate,checkTypes,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// externs from test_files/blacklisted_ambient_external_module/blacklisted.d.ts:
// Derived from: declare module "ambient-external-module-blacklisted"
/** @const */
var ambient_external_module_blacklisted = {};
/**
 * @record
 * @struct
 */
ambient_external_module_blacklisted.Ambient = function() {};
/** @type {string} */
ambient_external_module_blacklisted.Ambient.prototype.x;
