/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: test_files/export/export_helper_2.ts
/** @const */
var test_files$export$export_helper_2 = {};

/** @typedef {{a: number}} */
test_files$export$export_helper_2.DeclaredType;
/**
 * @record
 * @struct
 */
test_files$export$export_helper_2.DeclaredInterface = function() {};
/** @type {number} */
test_files$export$export_helper_2.DeclaredInterface.prototype.a;
