/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.

/** @typedef {{a: number}} */
var DeclaredType;
/**
 * @record
 * @struct
 */
function DeclaredInterface() {}
 /** @type {number} */
DeclaredInterface.prototype.a;
